### PR TITLE
Clean up nonconforming class/CSS

### PR DESCRIPTION
**Pull request by weijia-cheng**
Another example of the superfluous `newspaper` class

### CODE REVIEW

**Comment by acabal** [comment]
In general, we don't want to add elements like `<b>` if a selector would do instead. Can you target that blockquote specifically?

Are you sure this doesn't change the style of any other elements? `se compare-versions` will come in handy again here.

**Comment by weijia-cheng** [comment]
I updated to remove the `<b>`. This only affects the one file:

```
wcheng@pop-os:~/git/philip-k-dick_short-fiction$ se compare-versions .
Difference in the-skull.xhtml
```

```
wcheng@pop-os:~/git/philip-k-dick_short-fiction$ se xpath '//blockquote/header' .
/home/wcheng/git/philip-k-dick_short-fiction/src/epub/text/the-skull.xhtml
        <header>
                                                <p>Prisoner Hangs Self</p>
                                        </header>

        <header>
                                                <p>Man Arrested for Unlicensed 
Demonstration</p>
                                        </header>

```

**Comment by acabal** [comment]
But we still want the small caps. How can we get small caps on that header without a `<b>`? `se compare-versions` should state no differences.

**Comment by acabal** [comment]
Also don't forget that we allow classes if we have an actual *class* of elements to style. We only avoid classes as cheap one-off style hooks used by people who don't know that more elegant selectors exist.

**Comment by weijia-cheng** [comment]
The difference is in `the-skull` (not `the-gun` which is where I had added the `<b>` earlier) because the custom CSS here didn't have a 1em margin in the header, which the modified manual CSS does have. The blockquote in "The Gun" is directly targeted with the `#the-gun blockquote` rule which I restored to the original version.

Yeah, I know that we allow classes in some cases, though here I'm pretty sure it's superfluous since we can do the same by using CSS from the manual.

**Comment by acabal** [comment]
OK got it, thanks!

**Pull request merged**
