### PR TITLE
Add "Prize Ship".

### PR DESCRIPTION
**Pull request by adambuchbinder**
This imports "Prize Ship" from Project Gutenberg.

### CODE REVIEW

**Comment by acabal** [comment]
- There appear to be merge conflicts that need to be addressed before I can merge this in. 
- Why did you reorder the ToC?
- The story has not been typogrified
- Did you run `se modernize-spelling` and also go through our step by step guide applied to this story?
- Can you rebase commit [5acdddd](https://github.com/standardebooks/philip-k-dick_short-fiction/pull/6/commits/5acdddd7b8c736378b634189c95efedaacc78a16) out? It looks like a noop merge commit for some reason, just history pollution.

**Comment by adambuchbinder** [comment]
Well, that's embarrassing. I forgot to force-push the fix I'd made to un-reorder the spine (`se build-spine` blindly reorders things), and I'd completely forgotten to semanticate it and do the other little bits. That's all done now, pardon the errors.

**Comment by acabal** [comment]
OK thanks. There is still commit eb3daecdc4820abf0876a1a70b984b0cdaaa1f8c which looks like some kind of merge commit that I don't understand. It again reorders the ToC. We want descriptive commits that do real work, not merge commits which just clutter history.

**Comment by adambuchbinder** [comment]
Ah, I figured it out. I'd made my commits _before_ you removed the bridgeheads, so a merge was necessary. (And pardon the reordering; I'd fixed `content.opf` but not `toc.xhtml`.) I've rebased my commits to occur _after_ the removal of the bridgeheads, so there's no merge commit required. I think this should be good now.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
